package types

import (
	"cosmossdk.io/errors"
)

var (
	ErrAlreadyAllowlisted           = errors.Register("core", 2, "public key already exists in allowlist")
	ErrNotAllowlisted               = errors.Register("core", 3, "public key is not in allowlist")
	ErrInsufficientStake            = errors.Register("core", 4, "stake amount is insufficient")
	ErrInvalidStakeProof            = errors.Register("core", 5, "invalid stake proof")
	ErrZeroReplicationFactor        = errors.Register("core", 6, "replication factor cannot be zero")
	ErrGasPriceTooLow               = errors.Register("core", 7, "gas price is too low")
	ErrGasPriceTooHigh              = errors.Register("core", 8, "gas price is too high")
	ErrExecGasLimitTooLow           = errors.Register("core", 9, "exec gas limit is too low")
	ErrTallyGasLimitTooLow          = errors.Register("core", 10, "tally gas limit is too low")
	ErrInvalidLengthExecProgramID   = errors.Register("core", 11, "hex-encoded exec program ID is not 64 characters long")
	ErrInvalidLengthTallyProgramID  = errors.Register("core", 12, "hex-encoded tally program ID is not 64 characters long")
	ErrExecInputLimitExceeded       = errors.Register("core", 13, "exec input limit exceeded")
	ErrTallyInputLimitExceeded      = errors.Register("core", 14, "tally input limit exceeded")
	ErrConsensusFilterLimitExceeded = errors.Register("core", 15, "consensus filter limit exceeded")
	ErrMemoLimitExceeded            = errors.Register("core", 16, "memo limit exceeded")
	ErrPaybackAddressLimitExceeded  = errors.Register("core", 17, "payback address limit exceeded")
	ErrSedaPayloadLimitExceeded     = errors.Register("core", 18, "seda payload limit exceeded")
	ErrReplicationFactorTooHigh     = errors.Register("core", 19, "replication factor is too high")
	ErrDataRequestAlreadyExists     = errors.Register("core", 20, "data request already exists")
	ErrNotCommitting                = errors.Register("core", 21, "data request is not in committing state")
	ErrAlreadyCommitted             = errors.Register("core", 22, "commit under given public key already exists")
	ErrCommitTimeout                = errors.Register("core", 23, "commit timeout")
	ErrRevealNotStarted             = errors.Register("core", 24, "reveal phase has not started")
	ErrDataRequestExpired           = errors.Register("core", 25, "data request expired")
	ErrNotCommitted                 = errors.Register("core", 26, "commit under given public key does not exist")
	ErrAlreadyRevealed              = errors.Register("core", 27, "reveal under given public key already exists")
	ErrRevealTimeout                = errors.Register("core", 28, "reveal timeout")
	ErrRevealTooBig                 = errors.Register("core", 29, "reveal is too big")
	ErrRevealMismatch               = errors.Register("core", 30, "revealed result does not match the committed result")
	ErrInvalidCommitProof           = errors.Register("core", 31, "invalid commit proof")
	ErrInvalidRevealProof           = errors.Register("core", 32, "invalid reveal proof")
)
