// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sedachain/wasm_storage/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// The request message for QueryDataRequestWasm RPC.
type QueryDataRequestWasmRequest struct {
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *QueryDataRequestWasmRequest) Reset()         { *m = QueryDataRequestWasmRequest{} }
func (m *QueryDataRequestWasmRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDataRequestWasmRequest) ProtoMessage()    {}
func (*QueryDataRequestWasmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{0}
}
func (m *QueryDataRequestWasmRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDataRequestWasmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDataRequestWasmRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDataRequestWasmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataRequestWasmRequest.Merge(m, src)
}
func (m *QueryDataRequestWasmRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDataRequestWasmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataRequestWasmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataRequestWasmRequest proto.InternalMessageInfo

func (m *QueryDataRequestWasmRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// The response message for QueryDataRequestWasm RPC.
type QueryDataRequestWasmResponse struct {
	Wasm *Wasm `protobuf:"bytes,1,opt,name=wasm,proto3" json:"wasm,omitempty"`
}

func (m *QueryDataRequestWasmResponse) Reset()         { *m = QueryDataRequestWasmResponse{} }
func (m *QueryDataRequestWasmResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDataRequestWasmResponse) ProtoMessage()    {}
func (*QueryDataRequestWasmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{1}
}
func (m *QueryDataRequestWasmResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDataRequestWasmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDataRequestWasmResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDataRequestWasmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataRequestWasmResponse.Merge(m, src)
}
func (m *QueryDataRequestWasmResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDataRequestWasmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataRequestWasmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataRequestWasmResponse proto.InternalMessageInfo

func (m *QueryDataRequestWasmResponse) GetWasm() *Wasm {
	if m != nil {
		return m.Wasm
	}
	return nil
}

// The request message for QueryDataRequestWasms RPC.
type QueryDataRequestWasmsRequest struct {
}

func (m *QueryDataRequestWasmsRequest) Reset()         { *m = QueryDataRequestWasmsRequest{} }
func (m *QueryDataRequestWasmsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDataRequestWasmsRequest) ProtoMessage()    {}
func (*QueryDataRequestWasmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{2}
}
func (m *QueryDataRequestWasmsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDataRequestWasmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDataRequestWasmsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDataRequestWasmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataRequestWasmsRequest.Merge(m, src)
}
func (m *QueryDataRequestWasmsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDataRequestWasmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataRequestWasmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataRequestWasmsRequest proto.InternalMessageInfo

// The response message for QueryDataRequestWasms RPC.
type QueryDataRequestWasmsResponse struct {
	HashTypePairs []string `protobuf:"bytes,1,rep,name=hash_type_pairs,json=hashTypePairs,proto3" json:"hash_type_pairs,omitempty"`
}

func (m *QueryDataRequestWasmsResponse) Reset()         { *m = QueryDataRequestWasmsResponse{} }
func (m *QueryDataRequestWasmsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDataRequestWasmsResponse) ProtoMessage()    {}
func (*QueryDataRequestWasmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{3}
}
func (m *QueryDataRequestWasmsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDataRequestWasmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDataRequestWasmsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDataRequestWasmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDataRequestWasmsResponse.Merge(m, src)
}
func (m *QueryDataRequestWasmsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDataRequestWasmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDataRequestWasmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDataRequestWasmsResponse proto.InternalMessageInfo

func (m *QueryDataRequestWasmsResponse) GetHashTypePairs() []string {
	if m != nil {
		return m.HashTypePairs
	}
	return nil
}

// The request message for QueryOverlayWasm RPC.
type QueryOverlayWasmRequest struct {
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *QueryOverlayWasmRequest) Reset()         { *m = QueryOverlayWasmRequest{} }
func (m *QueryOverlayWasmRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOverlayWasmRequest) ProtoMessage()    {}
func (*QueryOverlayWasmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{4}
}
func (m *QueryOverlayWasmRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOverlayWasmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOverlayWasmRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOverlayWasmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOverlayWasmRequest.Merge(m, src)
}
func (m *QueryOverlayWasmRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOverlayWasmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOverlayWasmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOverlayWasmRequest proto.InternalMessageInfo

func (m *QueryOverlayWasmRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// The response message for QueryOverlayWasm RPC.
type QueryOverlayWasmResponse struct {
	Wasm *Wasm `protobuf:"bytes,1,opt,name=wasm,proto3" json:"wasm,omitempty"`
}

func (m *QueryOverlayWasmResponse) Reset()         { *m = QueryOverlayWasmResponse{} }
func (m *QueryOverlayWasmResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOverlayWasmResponse) ProtoMessage()    {}
func (*QueryOverlayWasmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{5}
}
func (m *QueryOverlayWasmResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOverlayWasmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOverlayWasmResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOverlayWasmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOverlayWasmResponse.Merge(m, src)
}
func (m *QueryOverlayWasmResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOverlayWasmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOverlayWasmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOverlayWasmResponse proto.InternalMessageInfo

func (m *QueryOverlayWasmResponse) GetWasm() *Wasm {
	if m != nil {
		return m.Wasm
	}
	return nil
}

// The request message for QueryOverlayWasms RPC.
type QueryOverlayWasmsRequest struct {
}

func (m *QueryOverlayWasmsRequest) Reset()         { *m = QueryOverlayWasmsRequest{} }
func (m *QueryOverlayWasmsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOverlayWasmsRequest) ProtoMessage()    {}
func (*QueryOverlayWasmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{6}
}
func (m *QueryOverlayWasmsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOverlayWasmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOverlayWasmsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOverlayWasmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOverlayWasmsRequest.Merge(m, src)
}
func (m *QueryOverlayWasmsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOverlayWasmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOverlayWasmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOverlayWasmsRequest proto.InternalMessageInfo

// The response message for QueryOverlayWasms RPC.
type QueryOverlayWasmsResponse struct {
	HashTypePairs []string `protobuf:"bytes,1,rep,name=hash_type_pairs,json=hashTypePairs,proto3" json:"hash_type_pairs,omitempty"`
}

func (m *QueryOverlayWasmsResponse) Reset()         { *m = QueryOverlayWasmsResponse{} }
func (m *QueryOverlayWasmsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOverlayWasmsResponse) ProtoMessage()    {}
func (*QueryOverlayWasmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{7}
}
func (m *QueryOverlayWasmsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOverlayWasmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOverlayWasmsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOverlayWasmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOverlayWasmsResponse.Merge(m, src)
}
func (m *QueryOverlayWasmsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOverlayWasmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOverlayWasmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOverlayWasmsResponse proto.InternalMessageInfo

func (m *QueryOverlayWasmsResponse) GetHashTypePairs() []string {
	if m != nil {
		return m.HashTypePairs
	}
	return nil
}

// The request message for QueryProxyContractRegistry RPC.
type QueryProxyContractRegistryRequest struct {
}

func (m *QueryProxyContractRegistryRequest) Reset()         { *m = QueryProxyContractRegistryRequest{} }
func (m *QueryProxyContractRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProxyContractRegistryRequest) ProtoMessage()    {}
func (*QueryProxyContractRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{8}
}
func (m *QueryProxyContractRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProxyContractRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProxyContractRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProxyContractRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProxyContractRegistryRequest.Merge(m, src)
}
func (m *QueryProxyContractRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProxyContractRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProxyContractRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProxyContractRegistryRequest proto.InternalMessageInfo

// The response message for QueryProxyContractRegistry RPC.
type QueryProxyContractRegistryResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryProxyContractRegistryResponse) Reset()         { *m = QueryProxyContractRegistryResponse{} }
func (m *QueryProxyContractRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProxyContractRegistryResponse) ProtoMessage()    {}
func (*QueryProxyContractRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e3a991a3b0319b3, []int{9}
}
func (m *QueryProxyContractRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProxyContractRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProxyContractRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProxyContractRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProxyContractRegistryResponse.Merge(m, src)
}
func (m *QueryProxyContractRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProxyContractRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProxyContractRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProxyContractRegistryResponse proto.InternalMessageInfo

func (m *QueryProxyContractRegistryResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryDataRequestWasmRequest)(nil), "sedachain.wasm_storage.v1.QueryDataRequestWasmRequest")
	proto.RegisterType((*QueryDataRequestWasmResponse)(nil), "sedachain.wasm_storage.v1.QueryDataRequestWasmResponse")
	proto.RegisterType((*QueryDataRequestWasmsRequest)(nil), "sedachain.wasm_storage.v1.QueryDataRequestWasmsRequest")
	proto.RegisterType((*QueryDataRequestWasmsResponse)(nil), "sedachain.wasm_storage.v1.QueryDataRequestWasmsResponse")
	proto.RegisterType((*QueryOverlayWasmRequest)(nil), "sedachain.wasm_storage.v1.QueryOverlayWasmRequest")
	proto.RegisterType((*QueryOverlayWasmResponse)(nil), "sedachain.wasm_storage.v1.QueryOverlayWasmResponse")
	proto.RegisterType((*QueryOverlayWasmsRequest)(nil), "sedachain.wasm_storage.v1.QueryOverlayWasmsRequest")
	proto.RegisterType((*QueryOverlayWasmsResponse)(nil), "sedachain.wasm_storage.v1.QueryOverlayWasmsResponse")
	proto.RegisterType((*QueryProxyContractRegistryRequest)(nil), "sedachain.wasm_storage.v1.QueryProxyContractRegistryRequest")
	proto.RegisterType((*QueryProxyContractRegistryResponse)(nil), "sedachain.wasm_storage.v1.QueryProxyContractRegistryResponse")
}

func init() {
	proto.RegisterFile("sedachain/wasm_storage/v1/query.proto", fileDescriptor_0e3a991a3b0319b3)
}

var fileDescriptor_0e3a991a3b0319b3 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4f, 0x6b, 0x13, 0x41,
	0x14, 0xcf, 0x68, 0xb5, 0xf4, 0x55, 0xa9, 0x0c, 0x88, 0xe9, 0x5a, 0xd7, 0xba, 0x62, 0x09, 0xd8,
	0xec, 0x9a, 0xa4, 0xd8, 0x0a, 0xea, 0xc1, 0x0a, 0x1e, 0xdb, 0x46, 0x41, 0xf0, 0xb2, 0x4c, 0x93,
	0x61, 0xb3, 0x90, 0xec, 0x6c, 0x67, 0x26, 0xb1, 0x8b, 0x78, 0xf1, 0x13, 0x08, 0x7e, 0x0a, 0xc1,
	0x83, 0x67, 0xc1, 0xbb, 0x27, 0x29, 0x78, 0xf1, 0x28, 0x89, 0x1f, 0x44, 0x66, 0x32, 0x89, 0x49,
	0x93, 0x4d, 0xba, 0x7a, 0x9b, 0xcc, 0xbc, 0xdf, 0xbf, 0x37, 0x6f, 0xb2, 0x70, 0x47, 0xd0, 0x3a,
	0xa9, 0x35, 0x48, 0x18, 0x79, 0xaf, 0x89, 0x68, 0xf9, 0x42, 0x32, 0x4e, 0x02, 0xea, 0x75, 0x4a,
	0xde, 0x51, 0x9b, 0xf2, 0xc4, 0x8d, 0x39, 0x93, 0x0c, 0xaf, 0x0e, 0xcb, 0xdc, 0xd1, 0x32, 0xb7,
	0x53, 0xb2, 0xd6, 0x02, 0xc6, 0x82, 0x26, 0xf5, 0x48, 0x1c, 0x7a, 0x24, 0x8a, 0x98, 0x24, 0x32,
	0x64, 0x91, 0xe8, 0x03, 0xad, 0xcd, 0x74, 0xfe, 0x31, 0x22, 0x5d, 0xed, 0x94, 0xe0, 0xfa, 0x81,
	0x52, 0x7d, 0x4a, 0x24, 0xa9, 0xd2, 0xa3, 0x36, 0x15, 0xf2, 0x25, 0x11, 0x2d, 0xb3, 0xc4, 0x18,
	0x16, 0x1a, 0x44, 0x34, 0xf2, 0x68, 0x1d, 0x15, 0x96, 0xaa, 0x7a, 0xed, 0x3c, 0x87, 0xb5, 0xe9,
	0x10, 0x11, 0xb3, 0x48, 0x50, 0x5c, 0x81, 0x05, 0x25, 0xa4, 0x31, 0xcb, 0xe5, 0x9b, 0x6e, 0x6a,
	0x10, 0x57, 0xc3, 0x74, 0xb1, 0x63, 0x4f, 0x27, 0x15, 0x66, 0xed, 0x3c, 0x83, 0x1b, 0x29, 0xe7,
	0x46, 0x75, 0x03, 0x56, 0x94, 0x3b, 0x5f, 0x26, 0x31, 0xf5, 0x63, 0x12, 0x72, 0x91, 0x47, 0xeb,
	0xe7, 0x0b, 0x4b, 0xd5, 0xcb, 0x6a, 0xfb, 0x45, 0x12, 0xd3, 0x7d, 0xb5, 0xe9, 0x14, 0xe1, 0x9a,
	0x26, 0xda, 0xeb, 0x50, 0xde, 0x24, 0xc9, 0xbc, 0xb0, 0x7b, 0x90, 0x9f, 0x2c, 0xff, 0x9f, 0xa0,
	0xd6, 0x24, 0xe1, 0x30, 0xe4, 0x2e, 0xac, 0x4e, 0x39, 0xcb, 0x18, 0xf0, 0x36, 0xdc, 0xd2, 0x24,
	0xfb, 0x9c, 0x1d, 0x27, 0xbb, 0x2c, 0x92, 0x9c, 0xd4, 0x64, 0x95, 0x06, 0xa1, 0x90, 0x3c, 0x19,
	0x28, 0x3d, 0x06, 0x67, 0x56, 0x91, 0x91, 0xcc, 0xc3, 0x22, 0xa9, 0xd7, 0x39, 0x15, 0xc2, 0xf4,
	0x64, 0xf0, 0xb3, 0xfc, 0x79, 0x11, 0x2e, 0x68, 0x02, 0xfc, 0x15, 0xc1, 0xca, 0xa9, 0x4b, 0xc1,
	0xf7, 0x67, 0xb4, 0x62, 0xc6, 0xb4, 0x59, 0xdb, 0x99, 0x71, 0x7d, 0xa3, 0xce, 0x83, 0x77, 0x3f,
	0x7e, 0x7f, 0x38, 0x57, 0xc1, 0x25, 0x4f, 0x11, 0x14, 0xff, 0x4e, 0x7f, 0x71, 0x30, 0xfd, 0x75,
	0x22, 0x89, 0xcf, 0xfb, 0x50, 0x5f, 0x9d, 0x78, 0x6f, 0x54, 0xdb, 0xde, 0xe2, 0x2f, 0x08, 0xae,
	0x9c, 0x1e, 0x2a, 0x9c, 0xd5, 0xc8, 0xe0, 0x06, 0xad, 0x9d, 0xec, 0x40, 0x13, 0xa1, 0xa2, 0x23,
	0x14, 0xf1, 0xdd, 0xb3, 0x47, 0x10, 0xf8, 0x13, 0x82, 0xe5, 0x91, 0x61, 0xc1, 0xe5, 0x79, 0xf2,
	0x93, 0x53, 0x6f, 0x55, 0x32, 0x61, 0x8c, 0xdb, 0x2d, 0xed, 0xd6, 0xc5, 0x9b, 0xa9, 0x6e, 0x59,
	0x1f, 0x35, 0xd6, 0xeb, 0x8f, 0x08, 0x2e, 0x8d, 0xce, 0x36, 0xce, 0xa2, 0x3d, 0xec, 0xf1, 0x56,
	0x36, 0x90, 0x71, 0xec, 0x6a, 0xc7, 0x05, 0xbc, 0x71, 0x26, 0xc7, 0x02, 0x7f, 0x47, 0x70, 0x75,
	0xea, 0xeb, 0xc0, 0x0f, 0xe7, 0xe9, 0xcf, 0x7a, 0x79, 0xd6, 0xa3, 0x7f, 0x44, 0x9b, 0x18, 0x3b,
	0x3a, 0x46, 0x19, 0xdf, 0x4b, 0x8d, 0x11, 0x2b, 0xbc, 0x5f, 0x33, 0x04, 0x3e, 0x37, 0x0c, 0x4f,
	0x0e, 0xbe, 0x75, 0x6d, 0x74, 0xd2, 0xb5, 0xd1, 0xaf, 0xae, 0x8d, 0xde, 0xf7, 0xec, 0xdc, 0x49,
	0xcf, 0xce, 0xfd, 0xec, 0xd9, 0xb9, 0x57, 0xdb, 0x41, 0x28, 0x1b, 0xed, 0x43, 0xb7, 0xc6, 0x5a,
	0x9a, 0x55, 0x7f, 0x19, 0x6a, 0xac, 0x39, 0x2a, 0x71, 0x3c, 0x2e, 0xa2, 0xfe, 0x84, 0xc4, 0xe1,
	0x45, 0x5d, 0x59, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x03, 0x35, 0xcc, 0xd3, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// DataRequestWasm returns Data Request Wasm given its hash.
	DataRequestWasm(ctx context.Context, in *QueryDataRequestWasmRequest, opts ...grpc.CallOption) (*QueryDataRequestWasmResponse, error)
	// DataRequestWasms returns all Data Request Wasms.
	DataRequestWasms(ctx context.Context, in *QueryDataRequestWasmsRequest, opts ...grpc.CallOption) (*QueryDataRequestWasmsResponse, error)
	// OverlayWasm returns Overlay Wasm given its hash.
	OverlayWasm(ctx context.Context, in *QueryOverlayWasmRequest, opts ...grpc.CallOption) (*QueryOverlayWasmResponse, error)
	// OverlayWasms returns all Overlay Wasms.
	OverlayWasms(ctx context.Context, in *QueryOverlayWasmsRequest, opts ...grpc.CallOption) (*QueryOverlayWasmsResponse, error)
	// ProxyContractRegistry returns the Proxy Contract Registry address.
	ProxyContractRegistry(ctx context.Context, in *QueryProxyContractRegistryRequest, opts ...grpc.CallOption) (*QueryProxyContractRegistryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DataRequestWasm(ctx context.Context, in *QueryDataRequestWasmRequest, opts ...grpc.CallOption) (*QueryDataRequestWasmResponse, error) {
	out := new(QueryDataRequestWasmResponse)
	err := c.cc.Invoke(ctx, "/sedachain.wasm_storage.v1.Query/DataRequestWasm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DataRequestWasms(ctx context.Context, in *QueryDataRequestWasmsRequest, opts ...grpc.CallOption) (*QueryDataRequestWasmsResponse, error) {
	out := new(QueryDataRequestWasmsResponse)
	err := c.cc.Invoke(ctx, "/sedachain.wasm_storage.v1.Query/DataRequestWasms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OverlayWasm(ctx context.Context, in *QueryOverlayWasmRequest, opts ...grpc.CallOption) (*QueryOverlayWasmResponse, error) {
	out := new(QueryOverlayWasmResponse)
	err := c.cc.Invoke(ctx, "/sedachain.wasm_storage.v1.Query/OverlayWasm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OverlayWasms(ctx context.Context, in *QueryOverlayWasmsRequest, opts ...grpc.CallOption) (*QueryOverlayWasmsResponse, error) {
	out := new(QueryOverlayWasmsResponse)
	err := c.cc.Invoke(ctx, "/sedachain.wasm_storage.v1.Query/OverlayWasms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProxyContractRegistry(ctx context.Context, in *QueryProxyContractRegistryRequest, opts ...grpc.CallOption) (*QueryProxyContractRegistryResponse, error) {
	out := new(QueryProxyContractRegistryResponse)
	err := c.cc.Invoke(ctx, "/sedachain.wasm_storage.v1.Query/ProxyContractRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// DataRequestWasm returns Data Request Wasm given its hash.
	DataRequestWasm(context.Context, *QueryDataRequestWasmRequest) (*QueryDataRequestWasmResponse, error)
	// DataRequestWasms returns all Data Request Wasms.
	DataRequestWasms(context.Context, *QueryDataRequestWasmsRequest) (*QueryDataRequestWasmsResponse, error)
	// OverlayWasm returns Overlay Wasm given its hash.
	OverlayWasm(context.Context, *QueryOverlayWasmRequest) (*QueryOverlayWasmResponse, error)
	// OverlayWasms returns all Overlay Wasms.
	OverlayWasms(context.Context, *QueryOverlayWasmsRequest) (*QueryOverlayWasmsResponse, error)
	// ProxyContractRegistry returns the Proxy Contract Registry address.
	ProxyContractRegistry(context.Context, *QueryProxyContractRegistryRequest) (*QueryProxyContractRegistryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) DataRequestWasm(ctx context.Context, req *QueryDataRequestWasmRequest) (*QueryDataRequestWasmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataRequestWasm not implemented")
}
func (*UnimplementedQueryServer) DataRequestWasms(ctx context.Context, req *QueryDataRequestWasmsRequest) (*QueryDataRequestWasmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataRequestWasms not implemented")
}
func (*UnimplementedQueryServer) OverlayWasm(ctx context.Context, req *QueryOverlayWasmRequest) (*QueryOverlayWasmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverlayWasm not implemented")
}
func (*UnimplementedQueryServer) OverlayWasms(ctx context.Context, req *QueryOverlayWasmsRequest) (*QueryOverlayWasmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverlayWasms not implemented")
}
func (*UnimplementedQueryServer) ProxyContractRegistry(ctx context.Context, req *QueryProxyContractRegistryRequest) (*QueryProxyContractRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyContractRegistry not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_DataRequestWasm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDataRequestWasmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DataRequestWasm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sedachain.wasm_storage.v1.Query/DataRequestWasm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DataRequestWasm(ctx, req.(*QueryDataRequestWasmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DataRequestWasms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDataRequestWasmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DataRequestWasms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sedachain.wasm_storage.v1.Query/DataRequestWasms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DataRequestWasms(ctx, req.(*QueryDataRequestWasmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OverlayWasm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOverlayWasmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OverlayWasm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sedachain.wasm_storage.v1.Query/OverlayWasm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OverlayWasm(ctx, req.(*QueryOverlayWasmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OverlayWasms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOverlayWasmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OverlayWasms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sedachain.wasm_storage.v1.Query/OverlayWasms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OverlayWasms(ctx, req.(*QueryOverlayWasmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProxyContractRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProxyContractRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProxyContractRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sedachain.wasm_storage.v1.Query/ProxyContractRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProxyContractRegistry(ctx, req.(*QueryProxyContractRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sedachain.wasm_storage.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataRequestWasm",
			Handler:    _Query_DataRequestWasm_Handler,
		},
		{
			MethodName: "DataRequestWasms",
			Handler:    _Query_DataRequestWasms_Handler,
		},
		{
			MethodName: "OverlayWasm",
			Handler:    _Query_OverlayWasm_Handler,
		},
		{
			MethodName: "OverlayWasms",
			Handler:    _Query_OverlayWasms_Handler,
		},
		{
			MethodName: "ProxyContractRegistry",
			Handler:    _Query_ProxyContractRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sedachain/wasm_storage/v1/query.proto",
}

func (m *QueryDataRequestWasmRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDataRequestWasmRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDataRequestWasmRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDataRequestWasmResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDataRequestWasmResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDataRequestWasmResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Wasm != nil {
		{
			size, err := m.Wasm.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDataRequestWasmsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDataRequestWasmsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDataRequestWasmsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDataRequestWasmsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDataRequestWasmsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDataRequestWasmsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HashTypePairs) > 0 {
		for iNdEx := len(m.HashTypePairs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HashTypePairs[iNdEx])
			copy(dAtA[i:], m.HashTypePairs[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.HashTypePairs[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryOverlayWasmRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOverlayWasmRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOverlayWasmRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOverlayWasmResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOverlayWasmResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOverlayWasmResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Wasm != nil {
		{
			size, err := m.Wasm.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOverlayWasmsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOverlayWasmsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOverlayWasmsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryOverlayWasmsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOverlayWasmsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOverlayWasmsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HashTypePairs) > 0 {
		for iNdEx := len(m.HashTypePairs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HashTypePairs[iNdEx])
			copy(dAtA[i:], m.HashTypePairs[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.HashTypePairs[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryProxyContractRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProxyContractRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProxyContractRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryProxyContractRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProxyContractRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProxyContractRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryDataRequestWasmRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDataRequestWasmResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Wasm != nil {
		l = m.Wasm.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDataRequestWasmsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDataRequestWasmsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.HashTypePairs) > 0 {
		for _, s := range m.HashTypePairs {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryOverlayWasmRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOverlayWasmResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Wasm != nil {
		l = m.Wasm.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOverlayWasmsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryOverlayWasmsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.HashTypePairs) > 0 {
		for _, s := range m.HashTypePairs {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryProxyContractRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryProxyContractRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryDataRequestWasmRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDataRequestWasmRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDataRequestWasmRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDataRequestWasmResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDataRequestWasmResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDataRequestWasmResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wasm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Wasm == nil {
				m.Wasm = &Wasm{}
			}
			if err := m.Wasm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDataRequestWasmsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDataRequestWasmsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDataRequestWasmsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDataRequestWasmsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDataRequestWasmsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDataRequestWasmsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashTypePairs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashTypePairs = append(m.HashTypePairs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOverlayWasmRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOverlayWasmRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOverlayWasmRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOverlayWasmResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOverlayWasmResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOverlayWasmResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wasm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Wasm == nil {
				m.Wasm = &Wasm{}
			}
			if err := m.Wasm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOverlayWasmsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOverlayWasmsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOverlayWasmsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOverlayWasmsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOverlayWasmsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOverlayWasmsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashTypePairs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashTypePairs = append(m.HashTypePairs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProxyContractRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProxyContractRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProxyContractRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProxyContractRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProxyContractRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProxyContractRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
