version: "2"
run:
  tests: false
  timeout: 10m
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - golint
        text: comment on exported var
      - linters:
          - golint
        text: don't use an underscore in package name
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - staticcheck
        text: 'ST1016:'
      - linters:
          - staticcheck
        path: legacy
        text: 'SA1019:'
      - linters:
        - revive
        text: 'var-naming: avoid meaningless package names'
    paths:
      - third_party$
      - builtin$
      - examples$
      - e2e/
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
  fix: true
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cometbft/cometbft)
        - prefix(github.com/CosmWasm)
        - prefix(github.com/cosmos)
        - prefix(github.com/cosmos/ibc)
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/sedaprotocol)
        - prefix(github.com/sedaprotocol/seda-chain)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
