FROM --platform=$BUILDPLATFORM golang:1.21 AS build-env
#FROM golang:1.21 AS build-env
# Install minimum necessary dependencies
RUN echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list

RUN apt-get update && apt-get install -y gcc-aarch64-linux-gnu goreleaser



WORKDIR /go/src/github.com/sedaprotocol/seda-chain

# Optimized fetching of dependencies
COPY go.mod go.sum ./

RUN go mod download

# Copy and build the project
COPY . .

# Dockerfile Cross-Compilation Guide
# https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide
ARG TARGETOS TARGETARCH

#RUN GOOS=$TARGETOS GOARCH=$TARGETARCH make build
RUN goreleaser build --snapshot --clean --skip-validate
RUN pwd
# Use alpine:3 as a base image
FROM alpine:3

RUN apk add --no-cache curl make bash jq sed

COPY --from=build-env /go/src/github.com/sedaprotocol/seda-chain/build/seda-chaind /usr/bin/seda-chaind

EXPOSE 26656 26657 1317 9090

CMD ["seda-chaind", "start"]
STOPSIGNAL SIGTERM
WORKDIR /root
