// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sedachain/batching/v1/batching.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Batch is an aggregation of data request results along with validator
// signatures used to prove these results on destination chains.
type Batch struct {
	// batch_number is a unique identifier of the batch incremented
	// every time a batch is created.
	BatchNumber uint64 `protobuf:"varint,1,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	// block_height is the height at which the batch was created.
	BlockHeight int64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// current_data_result_root is the hex-encoded root of the data result
	// merkle tree.
	CurrentDataResultRoot string `protobuf:"bytes,3,opt,name=current_data_result_root,json=currentDataResultRoot,proto3" json:"current_data_result_root,omitempty"`
	// data_result_root is the hex-encoded "super root" of the previous
	// data result and current data result roots.
	DataResultRoot string `protobuf:"bytes,4,opt,name=data_result_root,json=dataResultRoot,proto3" json:"data_result_root,omitempty"`
	// validator_root is the hex-encoded root of the validator merkle
	// tree.
	ValidatorRoot string `protobuf:"bytes,5,opt,name=validator_root,json=validatorRoot,proto3" json:"validator_root,omitempty"`
	// batch_id is the Keccack-256 hash of the batch content.
	BatchId []byte `protobuf:"bytes,6,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// proving_metadata is a field for additional proving data.
	ProvingMetadata []byte `protobuf:"bytes,7,opt,name=proving_metadata,json=provingMetadata,proto3" json:"proving_metadata,omitempty"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a028024867de2, []int{0}
}
func (m *Batch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return m.Size()
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

func (m *Batch) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Batch) GetCurrentDataResultRoot() string {
	if m != nil {
		return m.CurrentDataResultRoot
	}
	return ""
}

func (m *Batch) GetDataResultRoot() string {
	if m != nil {
		return m.DataResultRoot
	}
	return ""
}

func (m *Batch) GetValidatorRoot() string {
	if m != nil {
		return m.ValidatorRoot
	}
	return ""
}

func (m *Batch) GetBatchId() []byte {
	if m != nil {
		return m.BatchId
	}
	return nil
}

func (m *Batch) GetProvingMetadata() []byte {
	if m != nil {
		return m.ProvingMetadata
	}
	return nil
}

// DataResultTreeEntries is a list of data result tree entries for a
// given batch.
type DataResultTreeEntries struct {
	Entries [][]byte `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (m *DataResultTreeEntries) Reset()         { *m = DataResultTreeEntries{} }
func (m *DataResultTreeEntries) String() string { return proto.CompactTextString(m) }
func (*DataResultTreeEntries) ProtoMessage()    {}
func (*DataResultTreeEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a028024867de2, []int{1}
}
func (m *DataResultTreeEntries) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataResultTreeEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataResultTreeEntries.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataResultTreeEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResultTreeEntries.Merge(m, src)
}
func (m *DataResultTreeEntries) XXX_Size() int {
	return m.Size()
}
func (m *DataResultTreeEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResultTreeEntries.DiscardUnknown(m)
}

var xxx_messageInfo_DataResultTreeEntries proto.InternalMessageInfo

func (m *DataResultTreeEntries) GetEntries() [][]byte {
	if m != nil {
		return m.Entries
	}
	return nil
}

// ValidatorTreeEntry is an entry in the validator tree.
type ValidatorTreeEntry struct {
	ValidatorAddress   github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"validator_address,omitempty"`
	VotingPowerPercent uint32                                        `protobuf:"varint,2,opt,name=voting_power_percent,json=votingPowerPercent,proto3" json:"voting_power_percent,omitempty"`
	EthAddress         []byte                                        `protobuf:"bytes,3,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
}

func (m *ValidatorTreeEntry) Reset()         { *m = ValidatorTreeEntry{} }
func (m *ValidatorTreeEntry) String() string { return proto.CompactTextString(m) }
func (*ValidatorTreeEntry) ProtoMessage()    {}
func (*ValidatorTreeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a028024867de2, []int{2}
}
func (m *ValidatorTreeEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorTreeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorTreeEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorTreeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorTreeEntry.Merge(m, src)
}
func (m *ValidatorTreeEntry) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorTreeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorTreeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorTreeEntry proto.InternalMessageInfo

func (m *ValidatorTreeEntry) GetValidatorAddress() github_com_cosmos_cosmos_sdk_types.ValAddress {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *ValidatorTreeEntry) GetVotingPowerPercent() uint32 {
	if m != nil {
		return m.VotingPowerPercent
	}
	return 0
}

func (m *ValidatorTreeEntry) GetEthAddress() []byte {
	if m != nil {
		return m.EthAddress
	}
	return nil
}

// BatchSignatures contains basic validator data and its batch signatures
// under various cryptographic schemes.
type BatchSignatures struct {
	ValidatorAddress   github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"validator_address,omitempty"`
	Secp256K1Signature []byte                                        `protobuf:"bytes,2,opt,name=secp256k1_signature,json=secp256k1Signature,proto3" json:"secp256k1_signature,omitempty"`
}

func (m *BatchSignatures) Reset()         { *m = BatchSignatures{} }
func (m *BatchSignatures) String() string { return proto.CompactTextString(m) }
func (*BatchSignatures) ProtoMessage()    {}
func (*BatchSignatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a028024867de2, []int{3}
}
func (m *BatchSignatures) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchSignatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchSignatures.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchSignatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSignatures.Merge(m, src)
}
func (m *BatchSignatures) XXX_Size() int {
	return m.Size()
}
func (m *BatchSignatures) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSignatures.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSignatures proto.InternalMessageInfo

func (m *BatchSignatures) GetValidatorAddress() github_com_cosmos_cosmos_sdk_types.ValAddress {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *BatchSignatures) GetSecp256K1Signature() []byte {
	if m != nil {
		return m.Secp256K1Signature
	}
	return nil
}

// DataResult represents the result of a resolved data request.
type DataResult struct {
	// id is the Keccack-256 hash of the data result.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// dr_id is the data request identifier.
	DrId string `protobuf:"bytes,2,opt,name=dr_id,json=drId,proto3" json:"dr_id"`
	// dr_block_height is the height at which the data request was submitted.
	DrBlockHeight uint64 `protobuf:"varint,3,opt,name=dr_block_height,json=drBlockHeight,proto3" json:"dr_block_height"`
	// version is a semantic version string.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version"`
	// block_height is the height at which the data request was tallied.
	BlockHeight uint64 `protobuf:"varint,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height"`
	// block_timestamp is the unix timestamp in seconds of when the data request
	// was tallied.
	BlockTimestamp uint64 `protobuf:"varint,6,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp"`
	// exit_code is the exit code of the tally wasm binary execution.
	ExitCode uint32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code"`
	// gas_used is the gas used by the data request execution.
	GasUsed *cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=gas_used,json=gasUsed,proto3,customtype=cosmossdk.io/math.Int" json:"gas_used"`
	// result is the result of the tally wasm binary execution.
	Result []byte `protobuf:"bytes,9,opt,name=result,proto3" json:"result"`
	// payback_address is the payback address set by the relayer.
	PaybackAddress string `protobuf:"bytes,10,opt,name=payback_address,json=paybackAddress,proto3" json:"payback_address"`
	// seda_payload is the payload set by SEDA Protocol (e.g. OEV-enabled
	// data requests)
	SedaPayload string `protobuf:"bytes,11,opt,name=seda_payload,json=sedaPayload,proto3" json:"seda_payload"`
	// consensus indicates whether consensus was reached in the tally
	// process.
	Consensus bool `protobuf:"varint,12,opt,name=consensus,proto3" json:"consensus"`
}

func (m *DataResult) Reset()         { *m = DataResult{} }
func (m *DataResult) String() string { return proto.CompactTextString(m) }
func (*DataResult) ProtoMessage()    {}
func (*DataResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a028024867de2, []int{4}
}
func (m *DataResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResult.Merge(m, src)
}
func (m *DataResult) XXX_Size() int {
	return m.Size()
}
func (m *DataResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResult.DiscardUnknown(m)
}

var xxx_messageInfo_DataResult proto.InternalMessageInfo

func (m *DataResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataResult) GetDrId() string {
	if m != nil {
		return m.DrId
	}
	return ""
}

func (m *DataResult) GetDrBlockHeight() uint64 {
	if m != nil {
		return m.DrBlockHeight
	}
	return 0
}

func (m *DataResult) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DataResult) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *DataResult) GetBlockTimestamp() uint64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *DataResult) GetExitCode() uint32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *DataResult) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *DataResult) GetPaybackAddress() string {
	if m != nil {
		return m.PaybackAddress
	}
	return ""
}

func (m *DataResult) GetSedaPayload() string {
	if m != nil {
		return m.SedaPayload
	}
	return ""
}

func (m *DataResult) GetConsensus() bool {
	if m != nil {
		return m.Consensus
	}
	return false
}

// Params defines the parameters for the batching module.
type Params struct {
	// NumBatchesToKeep is the number of batches to keep in the state without
	// pruning.
	NumBatchesToKeep uint64 `protobuf:"varint,1,opt,name=num_batches_to_keep,json=numBatchesToKeep,proto3" json:"num_batches_to_keep,omitempty"`
	// MaxBatchPrunePerBlock is the maximum number of batches to prune per
	// block.
	MaxBatchPrunePerBlock uint64 `protobuf:"varint,2,opt,name=max_batch_prune_per_block,json=maxBatchPrunePerBlock,proto3" json:"max_batch_prune_per_block,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a028024867de2, []int{5}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetNumBatchesToKeep() uint64 {
	if m != nil {
		return m.NumBatchesToKeep
	}
	return 0
}

func (m *Params) GetMaxBatchPrunePerBlock() uint64 {
	if m != nil {
		return m.MaxBatchPrunePerBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Batch)(nil), "sedachain.batching.v1.Batch")
	proto.RegisterType((*DataResultTreeEntries)(nil), "sedachain.batching.v1.DataResultTreeEntries")
	proto.RegisterType((*ValidatorTreeEntry)(nil), "sedachain.batching.v1.ValidatorTreeEntry")
	proto.RegisterType((*BatchSignatures)(nil), "sedachain.batching.v1.BatchSignatures")
	proto.RegisterType((*DataResult)(nil), "sedachain.batching.v1.DataResult")
	proto.RegisterType((*Params)(nil), "sedachain.batching.v1.Params")
}

func init() {
	proto.RegisterFile("sedachain/batching/v1/batching.proto", fileDescriptor_5b2a028024867de2)
}

var fileDescriptor_5b2a028024867de2 = []byte{
	// 864 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0xae, 0xd3, 0x34, 0x3f, 0x93, 0xa4, 0x0d, 0xd3, 0x1b, 0xe4, 0xde, 0x45, 0x1c, 0x22, 0xae,
	0x14, 0x40, 0x49, 0x08, 0x11, 0x3f, 0x12, 0x6c, 0x30, 0x20, 0x51, 0xa1, 0x7b, 0x15, 0x0d, 0xe5,
	0x2e, 0x58, 0x60, 0x4d, 0x3c, 0x23, 0xc7, 0x4a, 0xec, 0x31, 0x33, 0xe3, 0xd0, 0xbe, 0x05, 0x2f,
	0xc0, 0x86, 0x67, 0xe0, 0x1d, 0x60, 0x79, 0xc5, 0x0a, 0x81, 0x64, 0xa1, 0x76, 0x97, 0x47, 0x60,
	0x85, 0x7c, 0xc6, 0x71, 0xda, 0xb2, 0x66, 0xe5, 0x39, 0xdf, 0x77, 0xce, 0x99, 0x73, 0x66, 0xbe,
	0x33, 0x46, 0x6f, 0x2a, 0xce, 0xa8, 0xbf, 0xa2, 0x61, 0x3c, 0x5d, 0x52, 0xed, 0xaf, 0xc2, 0x38,
	0x98, 0x6e, 0x67, 0xe5, 0x7a, 0x92, 0x48, 0xa1, 0x05, 0xee, 0x95, 0x5e, 0x93, 0x92, 0xd9, 0xce,
	0x9e, 0x5e, 0xf8, 0x42, 0x45, 0x42, 0x79, 0xe0, 0x34, 0x35, 0x86, 0x89, 0x78, 0xfa, 0x24, 0x10,
	0x81, 0x30, 0x78, 0xbe, 0x32, 0xe8, 0xf0, 0xa7, 0x0a, 0x3a, 0x71, 0xf3, 0x04, 0xf8, 0x0d, 0xd4,
	0x86, 0x4c, 0x5e, 0x9c, 0x46, 0x4b, 0x2e, 0x6d, 0x6b, 0x60, 0x8d, 0xaa, 0xa4, 0x05, 0xd8, 0x0b,
	0x80, 0xc0, 0x65, 0x23, 0xfc, 0xb5, 0xb7, 0xe2, 0x61, 0xb0, 0xd2, 0x76, 0x65, 0x60, 0x8d, 0x8e,
	0x49, 0x0b, 0xb0, 0x2f, 0x01, 0xc2, 0x1f, 0x22, 0xdb, 0x4f, 0xa5, 0xe4, 0xb1, 0xf6, 0x18, 0xd5,
	0xd4, 0x93, 0x5c, 0xa5, 0x1b, 0xed, 0x49, 0x21, 0xb4, 0x7d, 0x3c, 0xb0, 0x46, 0x4d, 0xd2, 0x2b,
	0xf8, 0xcf, 0xa9, 0xa6, 0x04, 0x58, 0x22, 0x84, 0xc6, 0x23, 0xd4, 0xfd, 0x4f, 0x40, 0x15, 0x02,
	0x4e, 0xd9, 0x43, 0xcf, 0x67, 0xe8, 0x74, 0x4b, 0x37, 0x21, 0xa3, 0x5a, 0x48, 0xe3, 0x77, 0x02,
	0x7e, 0x9d, 0x12, 0x05, 0xb7, 0x0b, 0xd4, 0x30, 0xfd, 0x84, 0xcc, 0xae, 0x0d, 0xac, 0x51, 0x9b,
	0xd4, 0xc1, 0xbe, 0x64, 0xf8, 0x2d, 0xd4, 0x4d, 0xa4, 0xd8, 0x86, 0x71, 0xe0, 0x45, 0x5c, 0xd3,
	0x3c, 0xbf, 0x5d, 0x07, 0x97, 0xb3, 0x02, 0x7f, 0x5e, 0xc0, 0xc3, 0x19, 0xea, 0x1d, 0x0a, 0xbd,
	0x92, 0x9c, 0x7f, 0x11, 0x6b, 0x19, 0x72, 0x85, 0x6d, 0x54, 0xe7, 0x66, 0x69, 0x5b, 0x83, 0xe3,
	0x3c, 0x7b, 0x61, 0x0e, 0x7f, 0xb5, 0x10, 0x7e, 0xb9, 0x2f, 0x65, 0x1f, 0x72, 0x83, 0xbf, 0x43,
	0xaf, 0x1d, 0xca, 0xa6, 0x8c, 0x49, 0xae, 0x14, 0x1c, 0x72, 0xdb, 0x9d, 0xfd, 0x93, 0x39, 0xe3,
	0x20, 0xd4, 0xab, 0x74, 0x39, 0xf1, 0x45, 0x54, 0xdc, 0x5b, 0xf1, 0x19, 0x2b, 0xb6, 0x9e, 0xea,
	0x9b, 0x84, 0xab, 0xc9, 0x4b, 0xba, 0xf9, 0xd4, 0x04, 0x92, 0x6e, 0x99, 0xab, 0x40, 0xf0, 0xbb,
	0xe8, 0xc9, 0x56, 0xe8, 0xbc, 0xa7, 0x44, 0xfc, 0xc0, 0xa5, 0x97, 0x70, 0xe9, 0xf3, 0xd8, 0x5c,
	0x52, 0x87, 0x60, 0xc3, 0x2d, 0x72, 0x6a, 0x61, 0x18, 0xec, 0xa0, 0x16, 0xd7, 0xab, 0xb2, 0x96,
	0x63, 0x38, 0x01, 0xc4, 0xf5, 0xaa, 0x48, 0x39, 0xfc, 0xd9, 0x42, 0x67, 0x20, 0x8e, 0xaf, 0xc3,
	0x20, 0xa6, 0x3a, 0x95, 0x5c, 0xfd, 0xef, 0x6d, 0x4c, 0xd1, 0xb9, 0xe2, 0x7e, 0xf2, 0xde, 0xfb,
	0x1f, 0xac, 0x67, 0x9e, 0xda, 0xef, 0x0b, 0x5d, 0xb4, 0x09, 0x2e, 0xa9, 0xb2, 0xa2, 0xe1, 0x5f,
	0x55, 0x84, 0x0e, 0x57, 0x84, 0x5f, 0x47, 0x95, 0x90, 0x41, 0x41, 0x4d, 0xb7, 0xb6, 0xcb, 0x9c,
	0x4a, 0xc8, 0x48, 0x25, 0x64, 0xb8, 0x8f, 0x4e, 0x98, 0xcc, 0xb5, 0x50, 0x01, 0xaa, 0xb9, 0xcb,
	0x1c, 0x03, 0x90, 0x2a, 0x93, 0x97, 0x0c, 0x7f, 0x8c, 0xce, 0x98, 0xf4, 0x1e, 0xc8, 0x3b, 0x3f,
	0x90, 0xaa, 0x7b, 0xbe, 0xcb, 0x9c, 0xc7, 0x14, 0xe9, 0x30, 0xe9, 0xde, 0x53, 0xfd, 0x33, 0x54,
	0xdf, 0x72, 0xa9, 0x42, 0x11, 0x1b, 0xcd, 0xba, 0xad, 0x5d, 0xe6, 0xec, 0x21, 0xb2, 0x5f, 0xe0,
	0xf9, 0xa3, 0xf9, 0x39, 0x81, 0x0d, 0xba, 0xbb, 0xcc, 0x79, 0x80, 0x3f, 0x9c, 0xa8, 0x4f, 0xd0,
	0x99, 0x21, 0x75, 0x18, 0x71, 0xa5, 0x69, 0x94, 0x80, 0x9c, 0x8b, 0xc2, 0x1e, 0x51, 0xe4, 0x14,
	0x80, 0xab, 0xbd, 0x8d, 0xdf, 0x46, 0x4d, 0x7e, 0x1d, 0x6a, 0xcf, 0x17, 0x8c, 0x83, 0xc6, 0x3b,
	0x6e, 0x67, 0x97, 0x39, 0x07, 0x90, 0x34, 0xf2, 0xe5, 0x67, 0x82, 0x71, 0xfc, 0x02, 0x35, 0x02,
	0xaa, 0xbc, 0x54, 0x71, 0x66, 0x37, 0xa0, 0x8d, 0xf9, 0x9f, 0x99, 0xd3, 0x33, 0xf7, 0xa7, 0xd8,
	0x7a, 0x12, 0x8a, 0x69, 0x44, 0xf5, 0x6a, 0x72, 0x19, 0xeb, 0x5d, 0xe6, 0x94, 0xce, 0xbf, 0xff,
	0x32, 0x46, 0xc5, 0x53, 0x73, 0x19, 0x6b, 0x52, 0x0f, 0xa8, 0xfa, 0x46, 0x71, 0x86, 0x87, 0xa8,
	0x66, 0xa6, 0xd9, 0x6e, 0x82, 0x3e, 0xd0, 0x2e, 0x73, 0x0a, 0x84, 0x14, 0xdf, 0xbc, 0xbb, 0x84,
	0xde, 0x2c, 0xa9, 0xbf, 0x2e, 0xc5, 0x84, 0x60, 0x6b, 0xe8, 0xee, 0x11, 0x45, 0x4e, 0x0b, 0x60,
	0x2f, 0x96, 0x39, 0x6a, 0xe7, 0xef, 0xa0, 0x97, 0xd0, 0x9b, 0x8d, 0xa0, 0xcc, 0x6e, 0x41, 0x28,
	0x1c, 0xe8, 0x7d, 0x9c, 0xb4, 0x72, 0x6b, 0x61, 0x0c, 0xfc, 0x0e, 0x6a, 0xfa, 0x22, 0x56, 0x3c,
	0x56, 0xa9, 0xb2, 0xdb, 0x03, 0x6b, 0xd4, 0x30, 0x47, 0x52, 0x82, 0xe4, 0xb0, 0x1c, 0x7e, 0x8f,
	0x6a, 0x0b, 0x2a, 0x69, 0xa4, 0xf0, 0x18, 0x9d, 0xc7, 0x69, 0xe4, 0xc1, 0x1b, 0xc2, 0x95, 0xa7,
	0x85, 0xb7, 0xe6, 0x3c, 0x29, 0x9e, 0xc9, 0x6e, 0x9c, 0x46, 0xae, 0x61, 0xae, 0xc4, 0x57, 0x9c,
	0x27, 0xf8, 0x23, 0x74, 0x11, 0xd1, 0x6b, 0xe3, 0xee, 0x25, 0x32, 0x8d, 0x79, 0x3e, 0x91, 0x46,
	0x45, 0xa0, 0xc1, 0x2a, 0xe9, 0x45, 0xf4, 0x1a, 0x82, 0x16, 0x39, 0xbd, 0xe0, 0x46, 0x52, 0xee,
	0xf3, 0xdf, 0x6e, 0xfb, 0xd6, 0xab, 0xdb, 0xbe, 0xf5, 0xf7, 0x6d, 0xdf, 0xfa, 0xf1, 0xae, 0x7f,
	0xf4, 0xea, 0xae, 0x7f, 0xf4, 0xc7, 0x5d, 0xff, 0xe8, 0xdb, 0xf9, 0xbd, 0xe1, 0xca, 0x3b, 0x82,
	0x27, 0xdc, 0x17, 0x1b, 0x30, 0xc6, 0xe6, 0x9f, 0x71, 0x7d, 0xf8, 0x6b, 0xc0, 0xb4, 0x2d, 0x6b,
	0xe0, 0x35, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x45, 0xd9, 0xf2, 0x15, 0x58, 0x06, 0x00, 0x00,
}

func (m *Batch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Batch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Batch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProvingMetadata) > 0 {
		i -= len(m.ProvingMetadata)
		copy(dAtA[i:], m.ProvingMetadata)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.ProvingMetadata)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BatchId) > 0 {
		i -= len(m.BatchId)
		copy(dAtA[i:], m.BatchId)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.BatchId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ValidatorRoot) > 0 {
		i -= len(m.ValidatorRoot)
		copy(dAtA[i:], m.ValidatorRoot)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.ValidatorRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DataResultRoot) > 0 {
		i -= len(m.DataResultRoot)
		copy(dAtA[i:], m.DataResultRoot)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.DataResultRoot)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CurrentDataResultRoot) > 0 {
		i -= len(m.CurrentDataResultRoot)
		copy(dAtA[i:], m.CurrentDataResultRoot)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.CurrentDataResultRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.BatchNumber != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.BatchNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DataResultTreeEntries) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataResultTreeEntries) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataResultTreeEntries) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Entries[iNdEx])
			copy(dAtA[i:], m.Entries[iNdEx])
			i = encodeVarintBatching(dAtA, i, uint64(len(m.Entries[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorTreeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorTreeEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorTreeEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EthAddress) > 0 {
		i -= len(m.EthAddress)
		copy(dAtA[i:], m.EthAddress)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.EthAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.VotingPowerPercent != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.VotingPowerPercent))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BatchSignatures) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchSignatures) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchSignatures) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Secp256K1Signature) > 0 {
		i -= len(m.Secp256K1Signature)
		copy(dAtA[i:], m.Secp256K1Signature)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.Secp256K1Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DataResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Consensus {
		i--
		if m.Consensus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.SedaPayload) > 0 {
		i -= len(m.SedaPayload)
		copy(dAtA[i:], m.SedaPayload)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.SedaPayload)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.PaybackAddress) > 0 {
		i -= len(m.PaybackAddress)
		copy(dAtA[i:], m.PaybackAddress)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.PaybackAddress)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x4a
	}
	if m.GasUsed != nil {
		{
			size := m.GasUsed.Size()
			i -= size
			if _, err := m.GasUsed.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintBatching(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.ExitCode != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.ExitCode))
		i--
		dAtA[i] = 0x38
	}
	if m.BlockTimestamp != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.BlockTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if m.BlockHeight != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x22
	}
	if m.DrBlockHeight != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.DrBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DrId) > 0 {
		i -= len(m.DrId)
		copy(dAtA[i:], m.DrId)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.DrId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintBatching(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxBatchPrunePerBlock != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.MaxBatchPrunePerBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.NumBatchesToKeep != 0 {
		i = encodeVarintBatching(dAtA, i, uint64(m.NumBatchesToKeep))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBatching(dAtA []byte, offset int, v uint64) int {
	offset -= sovBatching(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Batch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BatchNumber != 0 {
		n += 1 + sovBatching(uint64(m.BatchNumber))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovBatching(uint64(m.BlockHeight))
	}
	l = len(m.CurrentDataResultRoot)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.DataResultRoot)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.ValidatorRoot)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.BatchId)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.ProvingMetadata)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	return n
}

func (m *DataResultTreeEntries) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, b := range m.Entries {
			l = len(b)
			n += 1 + l + sovBatching(uint64(l))
		}
	}
	return n
}

func (m *ValidatorTreeEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	if m.VotingPowerPercent != 0 {
		n += 1 + sovBatching(uint64(m.VotingPowerPercent))
	}
	l = len(m.EthAddress)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	return n
}

func (m *BatchSignatures) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.Secp256K1Signature)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	return n
}

func (m *DataResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.DrId)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	if m.DrBlockHeight != 0 {
		n += 1 + sovBatching(uint64(m.DrBlockHeight))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovBatching(uint64(m.BlockHeight))
	}
	if m.BlockTimestamp != 0 {
		n += 1 + sovBatching(uint64(m.BlockTimestamp))
	}
	if m.ExitCode != 0 {
		n += 1 + sovBatching(uint64(m.ExitCode))
	}
	if m.GasUsed != nil {
		l = m.GasUsed.Size()
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.PaybackAddress)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	l = len(m.SedaPayload)
	if l > 0 {
		n += 1 + l + sovBatching(uint64(l))
	}
	if m.Consensus {
		n += 2
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumBatchesToKeep != 0 {
		n += 1 + sovBatching(uint64(m.NumBatchesToKeep))
	}
	if m.MaxBatchPrunePerBlock != 0 {
		n += 1 + sovBatching(uint64(m.MaxBatchPrunePerBlock))
	}
	return n
}

func sovBatching(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBatching(x uint64) (n int) {
	return sovBatching(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Batch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Batch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Batch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchNumber", wireType)
			}
			m.BatchNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentDataResultRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentDataResultRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataResultRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataResultRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = append(m.BatchId[:0], dAtA[iNdEx:postIndex]...)
			if m.BatchId == nil {
				m.BatchId = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProvingMetadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProvingMetadata = append(m.ProvingMetadata[:0], dAtA[iNdEx:postIndex]...)
			if m.ProvingMetadata == nil {
				m.ProvingMetadata = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataResultTreeEntries) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataResultTreeEntries: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataResultTreeEntries: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, make([]byte, postIndex-iNdEx))
			copy(m.Entries[len(m.Entries)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorTreeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorTreeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorTreeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = append(m.ValidatorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorAddress == nil {
				m.ValidatorAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPowerPercent", wireType)
			}
			m.VotingPowerPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPowerPercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthAddress = append(m.EthAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.EthAddress == nil {
				m.EthAddress = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchSignatures) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchSignatures: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchSignatures: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = append(m.ValidatorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorAddress == nil {
				m.ValidatorAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secp256K1Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Secp256K1Signature = append(m.Secp256K1Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Secp256K1Signature == nil {
				m.Secp256K1Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DrId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrBlockHeight", wireType)
			}
			m.DrBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DrBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTimestamp", wireType)
			}
			m.BlockTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitCode", wireType)
			}
			m.ExitCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExitCode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasUsed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.GasUsed = &v
			if err := m.GasUsed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result[:0], dAtA[iNdEx:postIndex]...)
			if m.Result == nil {
				m.Result = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaybackAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaybackAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SedaPayload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SedaPayload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consensus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Consensus = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBatching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumBatchesToKeep", wireType)
			}
			m.NumBatchesToKeep = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumBatchesToKeep |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBatchPrunePerBlock", wireType)
			}
			m.MaxBatchPrunePerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBatchPrunePerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBatching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBatching(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBatching
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatching
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBatching
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBatching
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBatching
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBatching        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBatching          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBatching = fmt.Errorf("proto: unexpected end of group")
)
