package types

const (
	EventTypeFastClient                    = "fast_client"
	EventTypeUser                          = "user"
	EventTypeRegisterFastClient            = "register_fast_client"
	EventTypeUpdateFastClient              = "update_fast_client"
	EventTypeTransferOwnership             = "transfer_ownership"
	EventTypeAcceptOwnership               = "accept_ownership"
	EventTypeCancelOwnershipTransfer       = "cancel_ownership_transfer"
	EventTypeAddUser                       = "add_user"
	EventTypeRemoveUser                    = "remove_user"
	EventTypeTopUpUser                     = "top_up_user"
	EventTypeExpireUserCredits             = "expire_credits"
	EventTypeSettleCredits                 = "settle_credits"
	EventTypeReport                        = "report"
	EventTypeSubmitReports                 = "submit_reports"
	EventTypeUseUserCredits                = "use_user_credits"
	EventTypeDataProxyPayout               = "data_proxy_payout"
	EventTypeInvalidDataProxyPayoutAddress = "invalid_data_proxy_payout_address"
	EventTypeUnregisteredDataProxy         = "unregistered_data_proxy"

	AttributeFastClientPubKey = "fast_client_pub_key"
	AttributeFastClientID     = "fast_client_id"
	AttributeOwnerAddress     = "owner_address"
	AttributeAdminAddress     = "admin_address"
	AttributeAddress          = "address"
	AttributeMemo             = "memo"
	AttributeBalance          = "balance"
	AttributeUsedCredits      = "used_credits"
	AttributeNewOwnerAddress  = "new_owner_address"
	AttributeUserID           = "user_id"
	//nolint:gosec // G101: These are not sensitive values
	AttributeInitialCredits         = "user_initial_credits"
	AttributeCredits                = "credits"
	AttributeSettleType             = "settle_type"
	AttributeAmount                 = "amount"
	AttributeDataProxyPubKey        = "data_proxy_pub_key"
	AttributeDataProxyPayoutAddress = "data_proxy_payout_address"
	AttributePrice                  = "price"
	AttributeQueries                = "queries"
)
