// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sedachain/data_proxy/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines data_proxy module's genesis state.
type GenesisState struct {
	Params           Params                 `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	DataProxyConfigs []DataProxyConfigs     `protobuf:"bytes,2,rep,name=data_proxy_configs,json=dataProxyConfigs,proto3" json:"data_proxy_configs"`
	FeeUpdateQueue   []FeeUpdateQueueRecord `protobuf:"bytes,3,rep,name=fee_update_queue,json=feeUpdateQueue,proto3" json:"fee_update_queue"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_614b9aebcf526c4f, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetDataProxyConfigs() []DataProxyConfigs {
	if m != nil {
		return m.DataProxyConfigs
	}
	return nil
}

func (m *GenesisState) GetFeeUpdateQueue() []FeeUpdateQueueRecord {
	if m != nil {
		return m.FeeUpdateQueue
	}
	return nil
}

// DataProxyConfigs define the data proxy entries in the registry.
type DataProxyConfigs struct {
	DataProxyPubkey string       `protobuf:"bytes,1,opt,name=data_proxy_pubkey,json=dataProxyPubkey,proto3" json:"data_proxy_pubkey,omitempty"`
	Config          *ProxyConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *DataProxyConfigs) Reset()         { *m = DataProxyConfigs{} }
func (m *DataProxyConfigs) String() string { return proto.CompactTextString(m) }
func (*DataProxyConfigs) ProtoMessage()    {}
func (*DataProxyConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_614b9aebcf526c4f, []int{1}
}
func (m *DataProxyConfigs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataProxyConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataProxyConfigs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataProxyConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataProxyConfigs.Merge(m, src)
}
func (m *DataProxyConfigs) XXX_Size() int {
	return m.Size()
}
func (m *DataProxyConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_DataProxyConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_DataProxyConfigs proto.InternalMessageInfo

func (m *DataProxyConfigs) GetDataProxyPubkey() string {
	if m != nil {
		return m.DataProxyPubkey
	}
	return ""
}

func (m *DataProxyConfigs) GetConfig() *ProxyConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// FeeUpdateQueueRecord defines an entry in the data proxy update queue.
type FeeUpdateQueueRecord struct {
	DataProxyPubkey string `protobuf:"bytes,1,opt,name=data_proxy_pubkey,json=dataProxyPubkey,proto3" json:"data_proxy_pubkey,omitempty"`
	UpdateHeight    int64  `protobuf:"varint,2,opt,name=update_height,json=updateHeight,proto3" json:"update_height,omitempty"`
}

func (m *FeeUpdateQueueRecord) Reset()         { *m = FeeUpdateQueueRecord{} }
func (m *FeeUpdateQueueRecord) String() string { return proto.CompactTextString(m) }
func (*FeeUpdateQueueRecord) ProtoMessage()    {}
func (*FeeUpdateQueueRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_614b9aebcf526c4f, []int{2}
}
func (m *FeeUpdateQueueRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeUpdateQueueRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeUpdateQueueRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeUpdateQueueRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeUpdateQueueRecord.Merge(m, src)
}
func (m *FeeUpdateQueueRecord) XXX_Size() int {
	return m.Size()
}
func (m *FeeUpdateQueueRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeUpdateQueueRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FeeUpdateQueueRecord proto.InternalMessageInfo

func (m *FeeUpdateQueueRecord) GetDataProxyPubkey() string {
	if m != nil {
		return m.DataProxyPubkey
	}
	return ""
}

func (m *FeeUpdateQueueRecord) GetUpdateHeight() int64 {
	if m != nil {
		return m.UpdateHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "sedachain.data_proxy.v1.GenesisState")
	proto.RegisterType((*DataProxyConfigs)(nil), "sedachain.data_proxy.v1.DataProxyConfigs")
	proto.RegisterType((*FeeUpdateQueueRecord)(nil), "sedachain.data_proxy.v1.FeeUpdateQueueRecord")
}

func init() {
	proto.RegisterFile("sedachain/data_proxy/v1/genesis.proto", fileDescriptor_614b9aebcf526c4f)
}

var fileDescriptor_614b9aebcf526c4f = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4e, 0xf2, 0x50,
	0x10, 0x85, 0x5b, 0xf8, 0x43, 0xf2, 0x5f, 0x50, 0xb1, 0x21, 0xb1, 0x61, 0x51, 0x08, 0x6a, 0x82,
	0x26, 0xb4, 0x01, 0xe3, 0x4e, 0x37, 0x68, 0xd4, 0x9d, 0x58, 0xe3, 0xc6, 0x84, 0x34, 0x97, 0x76,
	0x68, 0x1b, 0x85, 0x5b, 0xdb, 0x5b, 0x02, 0x89, 0x6f, 0xe0, 0xc6, 0xc7, 0x62, 0xc9, 0xd2, 0x95,
	0x31, 0xf0, 0x22, 0xa6, 0xd3, 0x06, 0x90, 0xd8, 0x85, 0xbb, 0xde, 0xe9, 0x37, 0x67, 0xce, 0x4c,
	0x0e, 0x39, 0x0c, 0xc0, 0xa2, 0xa6, 0x43, 0xdd, 0xa1, 0x66, 0x51, 0x4e, 0x0d, 0xcf, 0x67, 0xe3,
	0x89, 0x36, 0x6a, 0x6a, 0x36, 0x0c, 0x21, 0x70, 0x03, 0xd5, 0xf3, 0x19, 0x67, 0xd2, 0xde, 0x12,
	0x53, 0x57, 0x98, 0x3a, 0x6a, 0x96, 0x4b, 0x36, 0xb3, 0x19, 0x32, 0x5a, 0xf4, 0x15, 0xe3, 0xe5,
	0x7a, 0x9a, 0xea, 0x5a, 0x33, 0x92, 0xb5, 0xb7, 0x0c, 0x29, 0x5c, 0xc7, 0xa3, 0xee, 0x39, 0xe5,
	0x20, 0x9d, 0x93, 0x9c, 0x47, 0x7d, 0x3a, 0x08, 0x64, 0xb1, 0x2a, 0xd6, 0xf3, 0xad, 0x8a, 0x9a,
	0x32, 0x5a, 0xed, 0x20, 0xd6, 0xfe, 0x37, 0xfd, 0xac, 0x08, 0x7a, 0xd2, 0x24, 0x75, 0x89, 0xb4,
	0xa2, 0x0c, 0x93, 0x0d, 0xfb, 0xae, 0x1d, 0xc8, 0x99, 0x6a, 0xb6, 0x9e, 0x6f, 0x1d, 0xa5, 0x4a,
	0x5d, 0x52, 0x4e, 0x3b, 0xd1, 0xe3, 0x22, 0x6e, 0x48, 0x44, 0x8b, 0xd6, 0x46, 0x5d, 0xea, 0x92,
	0x62, 0x1f, 0xc0, 0x08, 0x3d, 0x8b, 0x72, 0x30, 0x5e, 0x42, 0x08, 0x41, 0xce, 0xa2, 0x78, 0x23,
	0x55, 0xfc, 0x0a, 0xe0, 0x01, 0xf9, 0xbb, 0x08, 0xd7, 0xc1, 0x64, 0xbe, 0x95, 0x0c, 0xd8, 0xee,
	0xff, 0xf8, 0x57, 0x7b, 0x25, 0xc5, 0x4d, 0x2b, 0xd2, 0x31, 0xd9, 0x5d, 0xdb, 0xc8, 0x0b, 0x7b,
	0x4f, 0x30, 0xc1, 0xdb, 0xfc, 0xd7, 0x77, 0x96, 0xfe, 0x3a, 0x58, 0x96, 0xce, 0x48, 0x2e, 0x5e,
	0x59, 0xce, 0xe0, 0xf1, 0x0e, 0xd2, 0x8f, 0xb7, 0x1a, 0xa1, 0x27, 0x3d, 0x35, 0x9b, 0x94, 0x7e,
	0xf3, 0xfa, 0x27, 0x07, 0xfb, 0x64, 0x2b, 0x39, 0x8e, 0x03, 0xae, 0xed, 0x70, 0x34, 0x92, 0xd5,
	0x0b, 0x71, 0xf1, 0x06, 0x6b, 0xed, 0xdb, 0xe9, 0x5c, 0x11, 0x67, 0x73, 0x45, 0xfc, 0x9a, 0x2b,
	0xe2, 0xfb, 0x42, 0x11, 0x66, 0x0b, 0x45, 0xf8, 0x58, 0x28, 0xc2, 0xe3, 0xa9, 0xed, 0x72, 0x27,
	0xec, 0xa9, 0x26, 0x1b, 0x68, 0x91, 0x75, 0x0c, 0x89, 0xc9, 0x9e, 0xf1, 0xd1, 0x88, 0x13, 0x35,
	0xc6, 0x14, 0x35, 0xe2, 0x4c, 0xf1, 0x89, 0x07, 0x41, 0x2f, 0x87, 0xdc, 0xc9, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x94, 0x5c, 0x28, 0x76, 0xce, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeeUpdateQueue) > 0 {
		for iNdEx := len(m.FeeUpdateQueue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeUpdateQueue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.DataProxyConfigs) > 0 {
		for iNdEx := len(m.DataProxyConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DataProxyConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *DataProxyConfigs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataProxyConfigs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataProxyConfigs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Config != nil {
		{
			size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DataProxyPubkey) > 0 {
		i -= len(m.DataProxyPubkey)
		copy(dAtA[i:], m.DataProxyPubkey)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DataProxyPubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FeeUpdateQueueRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeUpdateQueueRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeUpdateQueueRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdateHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UpdateHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DataProxyPubkey) > 0 {
		i -= len(m.DataProxyPubkey)
		copy(dAtA[i:], m.DataProxyPubkey)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DataProxyPubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.DataProxyConfigs) > 0 {
		for _, e := range m.DataProxyConfigs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FeeUpdateQueue) > 0 {
		for _, e := range m.FeeUpdateQueue {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *DataProxyConfigs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DataProxyPubkey)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Config != nil {
		l = m.Config.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *FeeUpdateQueueRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DataProxyPubkey)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.UpdateHeight != 0 {
		n += 1 + sovGenesis(uint64(m.UpdateHeight))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataProxyConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataProxyConfigs = append(m.DataProxyConfigs, DataProxyConfigs{})
			if err := m.DataProxyConfigs[len(m.DataProxyConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeUpdateQueue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeUpdateQueue = append(m.FeeUpdateQueue, FeeUpdateQueueRecord{})
			if err := m.FeeUpdateQueue[len(m.FeeUpdateQueue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataProxyConfigs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataProxyConfigs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataProxyConfigs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataProxyPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataProxyPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = &ProxyConfig{}
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeeUpdateQueueRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeUpdateQueueRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeUpdateQueueRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataProxyPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataProxyPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateHeight", wireType)
			}
			m.UpdateHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
