package types

const (
	EventTypeSophon                        = "sophon"
	EventTypeUser                          = "user"
	EventTypeRegisterSophon                = "register_sophon"
	EventTypeUpdateSophon                  = "update_sophon"
	EventTypeTransferOwnership             = "transfer_ownership"
	EventTypeAcceptOwnership               = "accept_ownership"
	EventTypeCancelOwnershipTransfer       = "cancel_ownership_transfer"
	EventTypeAddUser                       = "add_user"
	EventTypeRemoveUser                    = "remove_user"
	EventTypeTopUpUser                     = "top_up_user"
	EventTypeExpireUserCredits             = "expire_credits"
	EventTypeSettleCredits                 = "settle_credits"
	EventTypeReport                        = "report"
	EventTypeSubmitReports                 = "submit_reports"
	EventTypeUseUserCredits                = "use_user_credits"
	EventTypeDataProxyPayout               = "data_proxy_payout"
	EventTypeInvalidDataProxyPayoutAddress = "invalid_data_proxy_payout_address"
	EventTypeUnregisteredDataProxy         = "unregistered_data_proxy"

	AttributeSophonPubKey    = "sophon_pub_key"
	AttributeSophonID        = "sophon_id"
	AttributeOwnerAddress    = "owner_address"
	AttributeAdminAddress    = "admin_address"
	AttributeAddress         = "address"
	AttributeMemo            = "memo"
	AttributeBalance         = "balance"
	AttributeUsedCredits     = "used_credits"
	AttributeNewOwnerAddress = "new_owner_address"
	AttributeUserID          = "user_id"
	//nolint:gosec // G101: These are not sensitive values
	AttributeInitialCredits         = "user_initial_credits"
	AttributeCredits                = "credits"
	AttributeSettleType             = "settle_type"
	AttributeAmount                 = "amount"
	AttributeDataProxyPubKey        = "data_proxy_pub_key"
	AttributeDataProxyPayoutAddress = "data_proxy_payout_address"
	AttributePrice                  = "price"
	AttributeQueries                = "queries"
)
