name: Interchaintest

on:
  pull_request:
    push:
      branches:
        - main

env:
  GO_VERSION: "1.22.11"
  GOPRIVATE: github.com/sedaprotocol/vrf-go
  GITHUB_TOKEN: ${{ secrets.PAT }}
  TAR_PATH: /tmp/seda-docker-image.tar
  IMAGE_NAME: sedad-e2e
  SEDA_EXPONENT: ${{ secrets.SEDA_EXPONENT_ICT || 18 }}

permissions:
  contents: read
  repository-projects: read
  packages: read

concurrency:
  group: ci-${{ github.ref }}-interchaintest
  cancel-in-progress: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: interchaintest/go.sum

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.e2e
          tags: sedad-e2e
          build-args: SEDA_EXPONENT=${{ env.SEDA_EXPONENT }}
          outputs: type=docker,dest=${{ env.TAR_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.TAR_PATH }}

  interchaintest:
    needs: build-docker-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - "ictest-sdk-commands"
          - "ictest-sdk-boundaries"
          - "ictest-chain-start"
          - "ictest-state-sync"
          - "ictest-ibc-xfer"
          - "ictest-packet-forward-middleware"
          - "ictest-ibc-ica"
      fail-fast: false

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: interchaintest/go.sum

      - name: checkout chain
        uses: actions/checkout@v4

      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}
          path: /tmp

      - name: Load Docker Image
        run: |
          docker image load -i ${{ env.TAR_PATH }}
          docker image ls -a

      - name: Run Test
        run: make ${{ matrix.test }}
